<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Migration: Create AI Tables in fireteam schema
 *
 * Creates 4 new tables to support Whisper + Groq AI features:
 *   - fireteam.transcripts       — Raw audio transcripts per user/slide/chunk
 *   - fireteam.rubric_results    — Bloom's Taxonomy scores per student per rubric
 *   - fireteam.session_summaries — Markdown session summaries for instructors
 *   - fireteam.session_insights  — Conversation insight tags for analytics
 *
 * Also adds `explanation` column to fireteam.questions (Feature D).
 *
 * Run with: php artisan migrate
 */
return new class extends Migration
{
    public function up(): void
    {
        // ────────────────────────────────────────────────────
        // Table: fireteam.transcripts
        // Raw text from Groq Whisper, per user, per slide, per 30s chunk
        // ────────────────────────────────────────────────────
        DB::statement("
            CREATE TABLE IF NOT EXISTS fireteam.transcripts (
                id               BIGSERIAL PRIMARY KEY,
                session_id       BIGINT NOT NULL
                                   REFERENCES fireteam.sessions(id) ON DELETE CASCADE,
                experience_id    BIGINT NOT NULL
                                   REFERENCES fireteam.experiences(id),
                slide_id         BIGINT NOT NULL
                                   REFERENCES fireteam.slides(id),
                user_id          UUID NOT NULL,
                chunk_index      INT NOT NULL DEFAULT 0,
                transcript_text  TEXT NOT NULL,
                duration_seconds NUMERIC(8, 2),
                whisper_model    VARCHAR(50) NOT NULL DEFAULT 'whisper-large-v3',
                created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),

                CONSTRAINT uq_transcript_chunk
                    UNIQUE (session_id, slide_id, user_id, chunk_index)
            )
        ");

        DB::statement("
            CREATE INDEX IF NOT EXISTS idx_transcripts_session_user
                ON fireteam.transcripts(session_id, user_id)
        ");

        DB::statement("
            CREATE INDEX IF NOT EXISTS idx_transcripts_slide_user
                ON fireteam.transcripts(slide_id, user_id)
        ");

        // ────────────────────────────────────────────────────
        // Table: fireteam.rubric_results
        // AI evaluation scores — one row per student per rubric per session
        // ────────────────────────────────────────────────────
        DB::statement("
            CREATE TABLE IF NOT EXISTS fireteam.rubric_results (
                id             BIGSERIAL PRIMARY KEY,
                session_id     BIGINT NOT NULL
                                 REFERENCES fireteam.sessions(id) ON DELETE CASCADE,
                rubric_id      BIGINT NOT NULL
                                 REFERENCES fireteam.rubrics(id),
                user_id        UUID NOT NULL,
                score          SMALLINT NOT NULL DEFAULT 0
                                 CHECK (score BETWEEN 0 AND 6),
                arguments      JSONB NOT NULL DEFAULT '[]'::jsonb,
                justification  TEXT NOT NULL DEFAULT '',
                disagreements  JSONB NOT NULL DEFAULT '[]'::jsonb,
                groq_model     VARCHAR(100),
                prompt_tokens  INT,
                created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),

                CONSTRAINT uq_rubric_result
                    UNIQUE (session_id, rubric_id, user_id)
            )
        ");

        DB::statement("
            CREATE INDEX IF NOT EXISTS idx_rubric_results_session
                ON fireteam.rubric_results(session_id)
        ");

        DB::statement("
            CREATE INDEX IF NOT EXISTS idx_rubric_results_user
                ON fireteam.rubric_results(user_id)
        ");

        // ────────────────────────────────────────────────────
        // Table: fireteam.session_summaries
        // One markdown summary per session, generated by Groq LLM
        // ────────────────────────────────────────────────────
        DB::statement("
            CREATE TABLE IF NOT EXISTS fireteam.session_summaries (
                id                  BIGSERIAL PRIMARY KEY,
                session_id          BIGINT NOT NULL UNIQUE
                                      REFERENCES fireteam.sessions(id) ON DELETE CASCADE,
                summary_md          TEXT NOT NULL,
                group_balance_score NUMERIC(4, 3)
                                      CHECK (group_balance_score BETWEEN 0.0 AND 1.0),
                groq_model          VARCHAR(100),
                created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
        ");

        // ────────────────────────────────────────────────────
        // Table: fireteam.session_insights
        // Structured insight tags for Conversation Map analytics
        // ────────────────────────────────────────────────────
        DB::statement("
            CREATE TABLE IF NOT EXISTS fireteam.session_insights (
                id              BIGSERIAL PRIMARY KEY,
                session_id      BIGINT NOT NULL
                                  REFERENCES fireteam.sessions(id) ON DELETE CASCADE,
                insight_type    VARCHAR(50) NOT NULL
                                  CHECK (insight_type IN ('theme','missed_concept','strong_point','question_raised')),
                label           TEXT NOT NULL,
                relevance_score NUMERIC(4, 3) NOT NULL DEFAULT 0.5
                                  CHECK (relevance_score BETWEEN 0.0 AND 1.0),
                created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
            )
        ");

        DB::statement("
            CREATE INDEX IF NOT EXISTS idx_session_insights_session
                ON fireteam.session_insights(session_id)
        ");

        // ────────────────────────────────────────────────────
        // Alter: fireteam.questions — add explanation column
        // AI-generated explanation shown when student picks wrong answer
        // ────────────────────────────────────────────────────
        DB::statement("
            ALTER TABLE fireteam.questions
            ADD COLUMN IF NOT EXISTS explanation TEXT
        ");

        // ────────────────────────────────────────────────────
        // Alter: fireteam.sessions — add processing status column
        // Tracks whether evaluation has been triggered/completed
        // ────────────────────────────────────────────────────
        DB::statement("
            ALTER TABLE fireteam.sessions
            ADD COLUMN IF NOT EXISTS ai_status VARCHAR(20) NOT NULL DEFAULT 'pending'
        ");

        DB::statement("
            COMMENT ON COLUMN fireteam.sessions.ai_status IS
            'pending | processing | complete | failed'
        ");
    }

    public function down(): void
    {
        DB::statement('DROP TABLE IF EXISTS fireteam.session_insights CASCADE');
        DB::statement('DROP TABLE IF EXISTS fireteam.session_summaries CASCADE');
        DB::statement('DROP TABLE IF EXISTS fireteam.rubric_results CASCADE');
        DB::statement('DROP TABLE IF EXISTS fireteam.transcripts CASCADE');

        DB::statement('ALTER TABLE fireteam.questions DROP COLUMN IF EXISTS explanation');
        DB::statement('ALTER TABLE fireteam.sessions  DROP COLUMN IF EXISTS ai_status');
    }
};
